### ISSUE TITLE
Please reinstate Odysseyra1n

### ISSUE THREAD

**Issue by Babyyoda777** [asineth0/checkn1x#48]
Although you have said it’s garbage, it is still a useful feature to have. Unfortunately Odyssey1nx is unable to boot on my computer and I rely on Checkn1x to jailbreak. Thanks

**Comment by asineth0** [comment]
![](https://i.imgur.com/6cpffM4.jpg)

**Comment by asineth0** [comment]
On a more serious note though, I don't even use an iOS device anymore. I'll continue to update & maintain checkn1x, but adding new features is a bit out of scope.

I'd rather keep checkn1x small and stable, following UNIX philosophy: do one thing, do it well.

Also, look at it this way: The only important part of checkn1x is checkra1n, because that's the part you need Linux/macOS to run and that's the main reason checkn1x exists is to make running the tool easier for Windows users. The scrips for odysseyra1n require that you first jailbreak with checkra1n, but the scripts themselves could be run from any OS, including Windows. My suggestion would be to use checkn1x, and then reboot into another OS to run odysseyra1n from it instead.
