### ISSUE TITLE
[Virtualbox] Running Checkn1x from virtualbox gets stuck on grub welcome screen

### ISSUE THREAD

**Issue by ghost** [asineth0/checkn1x#5]
So since my computer is super slow to boot up I thought it would be good if I never had to shut it down in the first place.

I created the vm with everything default, hooked up my apple device so the vm could access it, but when I booted it up, it gets stuck on this screen:
![image](https://user-images.githubusercontent.com/67389459/99160011-8dcc2d00-26b0-11eb-9c44-68c3ec992fc7.png)
However, the first time I did it, actually booting from the usb I created with 3utools, it worked and I used checkra1n perfectly fine.

I also tried booting from the usb in virtualbox, but I couldn't get that to work out. Enabling EFI did get me to a grub console, but I'm not that good with linux and stuff...

Is this an error with checkn1x not being compatible with virtualbox or am I doing something wrong here?
Thanks in advance :)

**Comment by CTRL-ALT-EXIST** [comment]
More info:
Windows 10 home Version 10.0.19042 Build 19042
Virtualbox version 6.1.16 (Latest at the time of this post)
VBox Extension: 6.1.16r140961

**Comment by asineth0** [comment]
I can't whatever builds 3utools is distributing. They're out of date.

checkra1n doesn't function properly on VirtualBox. It's outside the scope of this project for me to try and fix this. Try switching your chipset in VirtualBox if GRUB can't boot the ISO image. 

checkn1x however does work on hypervisors, it works under QEMU/KVM on Linux, which I use for testing. So, this is a VirtualBox specific issue, probably in relation to the USB controller that it emulates, instead of a general issue of not running on virtual machines.
